
<?php
/** 
 * PHP Class Include File "faq.inc" generated by Poseidon for UML.
 * Poseidon for UML is developed by <A HREF="http://www.gentleware.com">Gentleware</A>.
 * Generated with <A HREF="http://jakarta.apache.org/velocity/">velocity</A> template engine.
 */
/**
 * Your documentation here ...
 */
class faq {

    // Attributes
    /**
     * Represent ...
     */
    var $faq_id;

    /**
     * Represent ...
     */
    var $faq_question;

    /**
     * Represent ...
     */
    var $faq_answer;

    /**
     * Represent ...
     */
    var $con;


    // Operations
    // Constructor
    /**
     * Does ...
     * @param conDb 
     */
    function faq($conDb) 
    { 
        // your code here
    } // end operation faq 

    /**
     * Does ...
     */
    function add() 
    { 
        // your code here
    } // end operation add 

    /**
     * Does ...
     * @param id 
     */
    function del($id) 
    { 
        // your code here
        return ;
    } // end operation del 

    /**
     * Does ...
     * @param id 
     */
    function update($id) 
    { 
        // your code here
        return ;
    } // end operation update 

    /**
     * Does ...
     */
    function list() 
    { 
        // your code here
    } // end operation list 

    /**
     * Does ...
     * @param id 
     */
    function info($id) 
    { 
        // your code here
    } // end operation info 

} // end class faq
?>
